# NUMPY

Array contains elements of same data type.
list has different data types.

In [ ]:
NUMPY is very powerful library.
it is NUMPY PACKED|LIBRARY|TOOLS|FRAMEWORK
NUMPY : matimatics+data structure+ statistial function+linear algebra
    NUMPY is labrary that handles array.

In [1]:
import numpy as np

In [3]:
np.__version__ #check version if numpy

'1.26.4'

In [4]:
import sys 
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# Creating array

In [6]:
my_list=[0,1,2,3]
my_list

[0, 1, 2, 3]

In [7]:
type(my_list)

list

# Converting list into in array

In [9]:
!pip install np

In [22]:
arr=np.array(my_list) #converting string into array
arr

array([0, 1, 2, 3])

In [23]:
type(arr)

numpy.ndarray

In [29]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
np.arange(3.0)

array([0., 1., 2.])

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [37]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
np.arange(20,10) #1st arg < 2nd arg 

array([], dtype=int32)

In [41]:
np.arange(-20,20)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19])

In [43]:
len(np.arange(-20,10))

30

In [45]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [47]:
np.arange(30,20) #1st arg always be < than 2nd one

array([], dtype=int32)

In [49]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [51]:
len(ar)

50

In [53]:
np.arange(10,10)

array([], dtype=int32)

In [55]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [57]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [59]:
np.zeros(3) #1d array parametre tunning

array([0., 0., 0.])

In [61]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [63]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [65]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [67]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
zero=np.zeros([2,2])
print(zero)

[[0. 0.]
 [0. 0.]]


In [71]:
np.zeros((10,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [73]:
np.ones(3)

array([1., 1., 1.])

In [75]:
np.ones(2)

array([1., 1.])

In [77]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [79]:
np.random.rand(5) #rand gives float no

array([0.97262795, 0.2530482 , 0.84299912, 0.14497451, 0.11370406])

In [81]:
np.random.rand(4)

array([0.92381662, 0.34117595, 0.38485257, 0.36481144])

In [83]:
np.random.rand(2,4) #2 rows and 4 columns

array([[0.31429686, 0.63860762, 0.44388868, 0.41779371],
       [0.49005673, 0.36965088, 0.38858931, 0.69672557]])

In [85]:
np.random.rand(3,5) #3 rows 5 columns

array([[0.99755665, 0.66826605, 0.99741485, 0.67607483, 0.60453427],
       [0.8320936 , 0.61322919, 0.88071198, 0.93512871, 0.15331494],
       [0.65652937, 0.98174146, 0.02661527, 0.61557611, 0.60847281]])

In [87]:
np.random.randint(3,5)

3

In [90]:
np.random.randint(10,20)

15

In [92]:
np.random.rand(3)

array([0.56018645, 0.72976384, 0.5205614 ])

In [94]:
np.random.randint(1) 

0

In [96]:
np.random.randint(10,20,30) #10*10 matrixs not between 10 to 30

array([15, 15, 10, 17, 17, 11, 17, 13, 17, 12, 14, 15, 13, 14, 14, 19, 15,
       10, 15, 10, 12, 13, 16, 15, 19, 18, 17, 11, 14, 13])

In [98]:
np.random.randint(2,20) #random interger no between 3&5 

9

In [100]:
np.random.randint(2,21)

9

In [102]:
np.random.randint(10,200,(10,10)) #10*10 matrix has between 10 to 40

array([[106, 173, 138,  83,  51,  39, 185,  40, 195,  96],
       [118, 127, 115, 140, 130,  98, 187, 129,  98,  35],
       [108, 124,  55, 107,  79, 107,  52,  23,  61,  64],
       [ 67,  51, 152, 136, 135,  50,  31, 170, 163, 176],
       [ 95,  21,  91, 172,  17,  86, 161,  32, 174, 109],
       [111, 183,  79, 127, 175,  70, 104,  26, 126, 192],
       [102, 181,  74,  36,  77, 165,  49, 170, 126, 106],
       [183,  37, 167, 141,  67,  88, 160,  27, 122, 138],
       [ 31,  63,  31, 167,  77, 198, 122,  43, 125, 171],
       [138, 117, 184, 169,  63,  22,  60,  32,  60,  80]])

In [104]:
np.random.randint(1,100,(12,12))

array([[55, 46, 82, 66, 87, 50,  3, 23, 36, 52, 13, 99],
       [ 5, 76, 14, 12, 23, 19, 62, 76, 96, 77, 61, 87],
       [ 2, 45, 89, 29, 40, 54,  1, 92, 11, 55,  5, 89],
       [23, 42, 41, 39, 96, 69, 55, 93, 95, 98,  3, 86],
       [88, 90, 88, 14, 78, 11, 71, 88, 81, 73, 65, 43],
       [ 6, 92, 65, 35,  2, 64, 89, 17, 64, 49, 89, 99],
       [ 3,  9, 19, 28, 89, 73, 72, 76, 88, 42, 88, 57],
       [51, 45, 65, 96, 47, 29, 14,  3, 19,  6, 12, 55],
       [46, 21,  1, 50, 46, 58, 68, 29, 66, 78, 80, 78],
       [ 3, 99, 86, 66,  5, 54, 35, 89,  7, 10, 49, 11],
       [33, 38, 50, 18, 98, 92, 65, 44, 69, 41, 63, 88],
       [41, 59, 30, 90, 21, 41,  8, 72, 58, 53, 40, 58]])

In [106]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [108]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [110]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [112]:
b=np.random.randint(10,20,(5,4)) #5*4matrix
b

array([[13, 14, 14, 10],
       [10, 11, 10, 17],
       [18, 14, 11, 17],
       [13, 18, 13, 17],
       [10, 15, 16, 17]])

In [114]:
type(b)

numpy.ndarray

In [116]:

b

array([[13, 14, 14, 10],
       [10, 11, 10, 17],
       [18, 14, 11, 17],
       [13, 18, 13, 17],
       [10, 15, 16, 17]])

In [118]:
b[1:3] # it will display entire row items(n-1)

array([[10, 11, 10, 17],
       [18, 14, 11, 17]])

In [120]:
b[:]

array([[13, 14, 14, 10],
       [10, 11, 10, 17],
       [18, 14, 11, 17],
       [13, 18, 13, 17],
       [10, 15, 16, 17]])

Operation

In [ ]:
a=np.random.randint(10,20,10)
a

In [125]:
id(a)

2841691133904

In [127]:
arr2=np.random.randint(0,100,(10,20))
arr2

array([[86, 14, 82, 17, 79,  7, 70, 89, 19,  4, 79, 70, 18, 88, 24, 72,
        36, 50, 49, 69],
       [24, 22, 82,  7, 33, 32, 57, 55, 48, 91, 48, 28, 79, 34, 15, 38,
        43, 38, 99,  3],
       [67, 95, 13, 82, 12, 20,  9, 38, 69, 40, 82, 91, 42, 10, 63, 53,
        10, 21, 62, 17],
       [32, 46, 27, 13, 94,  7, 55, 10, 84, 46, 42, 82, 74, 14, 98, 58,
        12, 84,  8, 24],
       [86, 53, 81, 61, 55, 71, 50, 32, 39, 92, 95, 65,  0, 47, 91, 71,
        48, 24, 66, 78],
       [86, 40,  0, 24, 52,  2,  7, 69, 14, 13, 62, 58, 90, 35, 82, 36,
        99, 63, 67, 93],
       [49, 50, 81, 96, 96, 60, 99,  4, 66, 34, 45, 89, 87, 83, 11, 33,
        73, 89, 50, 13],
       [79, 82, 21, 54, 61, 87, 95, 64, 35, 78, 92, 78, 91, 53, 74, 13,
        45, 79, 64, 29],
       [62, 12, 24, 91, 46, 68, 79, 44, 27, 97, 59, 86, 18, 16,  8, 18,
        50, 81, 11, 84],
       [54, 86, 16, 72, 24, 87, 32, 22, 58,  1, 94,  2, 89, 31, 76, 40,
        57, 37, 58, 12]])

In [129]:
arr2[2:4]

array([[67, 95, 13, 82, 12, 20,  9, 38, 69, 40, 82, 91, 42, 10, 63, 53,
        10, 21, 62, 17],
       [32, 46, 27, 13, 94,  7, 55, 10, 84, 46, 42, 82, 74, 14, 98, 58,
        12, 84,  8, 24]])

In [131]:
arr2[5:4]

array([], shape=(0, 20), dtype=int32)

In [133]:
arr2[3:] #from 3rd row

array([[32, 46, 27, 13, 94,  7, 55, 10, 84, 46, 42, 82, 74, 14, 98, 58,
        12, 84,  8, 24],
       [86, 53, 81, 61, 55, 71, 50, 32, 39, 92, 95, 65,  0, 47, 91, 71,
        48, 24, 66, 78],
       [86, 40,  0, 24, 52,  2,  7, 69, 14, 13, 62, 58, 90, 35, 82, 36,
        99, 63, 67, 93],
       [49, 50, 81, 96, 96, 60, 99,  4, 66, 34, 45, 89, 87, 83, 11, 33,
        73, 89, 50, 13],
       [79, 82, 21, 54, 61, 87, 95, 64, 35, 78, 92, 78, 91, 53, 74, 13,
        45, 79, 64, 29],
       [62, 12, 24, 91, 46, 68, 79, 44, 27, 97, 59, 86, 18, 16,  8, 18,
        50, 81, 11, 84],
       [54, 86, 16, 72, 24, 87, 32, 22, 58,  1, 94,  2, 89, 31, 76, 40,
        57, 37, 58, 12]])

In [138]:
arr2.max()

99

In [142]:
arr2.min()

0

In [147]:
arr2.mean()

51.56

In [151]:
arr2.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [157]:
from numpy import*
a=array([1,2,3,4,9])
median(a)

3.0

In [168]:
arr2.reshape(2,3,order='c')

ValueError: cannot reshape array of size 200 into shape (2,3)

In [172]:
mat=np.arange(0,100).reshape(10,10)